srecord: srecord Namespace Reference
srecord Namespace Reference
Classes
class adler16
The adler16 class is used to represent the running value of a 16-bit Adler checksum of series of bytes.
class adler32
The adler32 class is used to represent the running value of a 32-bit Adler checksum of series of bytes.
class arglex
The arglex class is used to implement a lexical analizer for command line arguments.
class arglex_tool
The srecord::arglex_tool is used to parse command line with srec-specific arguments.
class crc16
The crc16 class is used to represent the running value of a 16-bit cyclic redundancy check of series of bytes.
class crc32
The crc32 class is used to represent the running value of a 32-bit cyclic redundancy check of series of bytes.
class fletcher16
The fletcher16 class is used to represent the running value of a 16-bit Fletcher's Checksum of series of bytes.
class fletcher32
The fletcher32 class is used to represent the running value of a 32-bit Fletcher's Checksum of a series of bytes.
class input
The srecord::input class is used to represent an abstract EPROM load file source.
class input_catenate
The srecord::input_catenate class is used to represent an input source which presents two inoput sources as if they were a single input source.
class input_file
The srecord::input_file class is used to represent an generic input file.
class input_file_aomf
The srecord::input_file_aomf class is used to parse Intel Absolute Object Module Format (AOMF) file.
class input_file_ascii_hex
The srecord::input_file_ascii_hex class is used to repesent the parse state when reading an Ascii-Hex format input file.
class input_file_atmel_generic
The srecord::input_file_atmel_generic class is used to represent the parse stat of an Atmel Genric formatted file.
class input_file_binary
The srecord::input_file_binary class is used to represent the parse state of a binary input stream.
class input_file_brecord
The srecord::input_file_brecord class is used to represent the parse state of a Motorola MC68EZ328 bootstrap b-record format input file.
class input_file_cosmac
The srecord::input_file_cosmac class is used to represent the parse state when reading an RCS Cosmac formatted file.
class input_file_dec_binary
The srecord::input_file_dec_binary class is used to parse a DEC Binary (PDP 11 absolute loader XXDP) format file.
class input_file_emon52
The srecord::input_file_emon52 class is used to parse an EMON52 formatted file (Elektor Monitor, dunno what the 52 is for).
class input_file_fairchild
The srecord::input_file_fairchild class is used to represent the parse stat ewhen reading a file in Fairchild Fairbug format.
class input_file_fastload
The fastload class is used to parse an LSI Logic Fast Load format file.
class input_file_formatted_binary
The srecord::input_file_formatted_binary class is used to represent the parse state when reading a file in the Formatted Binary format.
class input_file_four_packed_code
The srecord::input_file_four_packed_code represents an input file in the four packed code (FPC) format.
class input_file_hexdump
The input_file_hexdump class is used to represent the processing required to read in a hexadecimal dump.
class input_file_hp64k
The srecord::input_file_hp64k class is used to represent the parse state of a HP64000 Absolute formatted input file.
class input_file_idt
The srecord::input_file_idt class is used to represent the parse state of a IDT/sim binary format input file.
class input_file_intel
The srecord::input_file_intel class is used to represent the parse state of an Intel Hex formatted file.
class input_file_intel16
The srecord::input_file_intel16 class is used to represent the parse state of an INHX16 formatted file.
class input_file_logisim
The input_file_logisim class is used to represent the processing required to parse Logisim rom data files.
class input_file_mif
The srecord::input_file_mif class is used to represent the parse state when reading a Memory Initialization File (MIF) formatted file.
class input_file_mips_flash
The srecord::input_file_mips_flash class is used to represent the parse state of a MIPS-Flash formatted input file.
class input_file_mos_tech
The mos_tech class is used to parse a MOS Technology format file.
class input_file_motorola
The srecord::input_file_motorola class is used to represent the parse state of a Motorola S-Record formatted input file.
class input_file_msbin
The srecord::input_file_binary class is used to represent the parse state of msbin (Windows CE Binary Image Data Format) input stream.
class input_file_needham
The srecord::input_file_needham class is used to represent the parse state of a file in Needham Hex format.
class input_file_os65v
The srecord::input_file_os65v class is used to represent the input state of an Ohio Scientific hexadecimal formatted file.
class input_file_ppb
The input_file_hexdump class is used to represent the processing required to read in a Stag Prom Programmer binary file.
class input_file_ppx
The input_file_hexdump class is used to represent the processing required to read in a Stag Prog Programmer hexadecimal file.
class input_file_signetics
The srecord::input_file_signetics class is used to represent reading a Signetics format file.
class input_file_spasm
The srecord::input_file_spasm class is used to represent the parse state of a SPASM formatted input file.
class input_file_spectrum
The srecord::input_file_spectrum class is used to represent the parse state when reading from a file in Spectrum format.
class input_file_stewie
The srecord::input_file_stewie class is used to represent the parse state of an input file in an undocumented binary format loosely based on the Motorola format.
class input_file_tektronix
The srecord::input_file_tektronix clas sis used to represent the parse state of an input file in Tektronix (non-extended) format.
class input_file_tektronix_extended
The srecord::input_file_tektronix_extended clas sis used to represent the parse state of an input file in Tektronix Extended format.
class input_file_ti_tagged
The srecord::input_file_ti_tagged class is used to represent the parse state of an input file in TI Tagged format.
class input_file_ti_tagged_16
The srecord::input_file_ti_tagged_16 class is used to represent the parse state of an input file in Texas Instruments SDSMAC 320 format.
class input_file_ti_txt
The srecord::input_file_ti_txt class is used to repesent the parse state when reading a ti_txt (MSP430) format input file.
class input_file_trs80
The srecord::input_file_trs80 class is used to parse a Radio Shack TRS-80 load module file.
class input_file_vmem
The srecord::input_file_vmem class is used to repesent the parse state when reading a Verilog VMEM format input file.
class input_file_wilson
The srecord::input_file_wilson clas sis used to represent the parse state of an input file in Wilson format.
class input_filter
The srecord::input_filter class is an abstract interface for all of the various filters that can be applied to an incoming EPROM file.
class input_filter_and
The srecord::input_filter_and clas sis used to represent the input state of a filter which bit-wise ANDs all incoming data bytes with a fixed value.
class input_filter_bitrev
The srecord::input_filter_bitrev clas sis used to represent the input state of a filter which reverses the order of bits in each data byte.
class input_filter_byte_swap
The srecord::input_filter_byte_swap class is used to reverse the even-addressed and odd-addressed bytes in an input source.
class input_filter_checksum
The srecord::input_filter_checksum class is an abstraction of various checksums to be ammplied to input sources.
class input_filter_checksum_bitnot
The srecord::input_filter_checksum_bitnot class is used to represent the state of a checksum filter that inserts a bitnot sum into the data.
class input_filter_checksum_negative
The srecord::input_filter_checksum_negative class is used to represent the state of a checksum filter that inserts a negative sum into the data.
class input_filter_checksum_positive
The srecord::input_filter_checksum_positive class is used to represent the state of a checksum filter that inserts a positive sum into the data.
class input_filter_crop
The srecord::input_filter_crop filter is used to crop the data by selecting portions of the address range to be passed through.
class input_filter_fill
The srecord::input_filter_fill class is used to represent a filter which replaces in set data locations with constant data.
class input_filter_interval
The srecord::input_filter_interval class is used to represent a filter which works with the interval representing the data's coverage, exclusive of where the result is to be placed.
class input_filter_interval_length
The srecord::input_filter_interval_length class is used to represent a filter which injects the maximum minus minimum addresses of the data into the data.
class input_filter_interval_maximum
The srecord::input_filter_interval_maximum class is used to represent a filter which injects the maximum address (last used address + 1) of the data into the data.
class input_filter_interval_minimum
The srecord::input_filter_interval_minimum class is used to represent a filter which injects the minimum address of the data into the data.
class input_filter_message
The srecord::input_filter_message class is used to represent an abstract base class for filters that must operate on the complete data, in order, in order to functions (e.g.
class input_filter_message_adler16
The srecord::input_filter_message_adler16 class is used to represent the state of a checksum filter that inserts an Adler 16 checksum into the data.
class input_filter_message_adler32
The srecord::input_filter_message_adler32 class is used to represent the state of a checksum filter that inserts an Adler 32 checksum into the data.
class input_filter_message_crc16
The srecord::input_filter_message_crc16 class is used to represent the state of a checksum filter that inserts a CRC16 into the data.
class input_filter_message_crc32
The srecord::input_filter_message_crc32 class is used to represent the state of a checksum filter that inserts a CRC32 into the data.
class input_filter_message_fletcher16
The srecord::input_filter_message_fletcher16 class is used to represent the state of a checksum filter that inserts an Fletcher 16 checksum into the data.
class input_filter_message_fletcher32
The srecord::input_filter_message_fletcher32 class is used to represent the state of a checksum filter that inserts an Fletcher 32 checksum into the data.
class input_filter_message_gcrypt
The srecord::input_filter_message_gcrypt class is used to represent a filter that runs the data through one of the hashing algorithms in the gcrypt library.
class input_filter_message_stm32
The input_filter_message_stm32 class represents the code required to calculate an STM32 (CRC) value.
class input_filter_not
The srecord::input_filter_not class is used to represent an input stream which bit-wise NOTs the data.
class input_filter_offset
The srecord::input_filter_offset class is used to represent a filetr where the addresses of the the deeper input source are offset by a number of bytes.
class input_filter_or
The srecord::input_filter_and clas sis used to represent the input state of a filter which bit-wise ORs all incoming data bytes with a fixed value.
class input_filter_random_fill
The srecord::input_filter_random_fill class is used to represent a filter which replaces in set data locations with random data.
class input_filter_sequence
The srecord::input_filter_sequence class is used to represent an input filter which does not change the data in any way, but issues warnings if the data is not instrictly ascending address order.
class input_filter_split
The srecord::input_filter_split class is used to represent a filter which splits ints input source into piceces.
class input_filter_unfill
The srecord::input_filter_unfill class is used to represent a filter which makes holes in the data wherever a specified data byte value appears.
class input_filter_unsplit
The srecord::input_filter_unsplit class is used to represent a filter whoch explosed the deeper input source.
class input_filter_xor
The srecord::input_filter_xor clas sis used to represent the input state of a filter which bit-wise XORs all incoming data bytes with a fixed value.
class input_generator
The srecord::input_generator class is used to represent the state of generating data from whole cloth.
class input_generator_constant
The srecord::input_generator_constant class is used to represent the state of a data generator which supplies constant bytes.
class input_generator_random
The srecord::input_generator_random class is used to represent a factory which manufactures random data.
class input_generator_repeat
The srecord::input_generator_repeat class is used to represent generating data which cycles over a fixed set of byte values.
class interval
The interval class is used to represent a set of integer values, usually composed of runs of adjacent value.
class memory
The srecord::memory class is used to simulate memory contents.
class memory_chunk
The srecord::memory_chunk class is used to represent portion of memory.
class memory_walker
The srecord::memory_walker class is used to represent an abstract handler for the action to perform when walking a memory image.
class memory_walker_adler16
The srecord::memory_walker_adler16 class is used to represent the parse state of a memory walker which calculates a running ADLER16 checksum.
class memory_walker_adler32
The srecord::memory_walker_adler32 class is used to represent the parse state of a memory walker which calculates a running ADLER32 checksum.
class memory_walker_alignment
The srecord::memory_walker_alignment class is used to represent the parse state of a memory walker which determines whether or not the data are well aligned.
class memory_walker_compare
The srecord::memory_walker_compare class is used to represent a memory walker which compares memory data with another memory instance.
class memory_walker_continuity
The srecord::memory_walker_crc16 class is used to represent the parse state of a memory walker which determines whether or not the data are continuous.
class memory_walker_crc16
The srecord::memory_walker_crc16 class is used to represent the parse state of a memory walker which calculates a running CRC16 checksum.
class memory_walker_crc32
The srecord::memory_walker_crc32 class is used to represent the parse state of a memory walker which calculates a running CRC32 checksum.
class memory_walker_fletcher16
The srecord::memory_walker_fletcher16 class is used to represent the parse state of a memory walker which calculates a running Fletcher-16 checksum.
class memory_walker_fletcher32
The srecord::memory_walker_fletcher32 class is used to represent the parse state of a memory walker which calculates a running Fletcher-32 checksum.
class memory_walker_gcrypt
The srecord::memory_walker_gcrypt class is used to represent walking memory and passing it to the gcrypt library in order to calculate a message digest.
class memory_walker_stm32
The memory_walker_stm32 class is a vistor for calculating the CRC used by the hardware CRC unit on the STM32 series of ARM MPUs.
class memory_walker_writer
The srecord::memory_walker_writer class is used to write data to an output stream when a memory image is walked.
class output
The srecord::output class is used to represent an abstract output vector.
class output_file
The srecord::output_file class is used to represent a generic output file.
class output_file_aomf
The srecord::output_file_aomf class is used to represent the output state of a file in Intel Absolute Object Module Format (AOMF).
class output_file_ascii_hex
The srecord::output_file_ascii_hex class is used to write a file in Ascii-Hex-Space format.
class output_file_asm
The srecord::output_file_asm class is used to represent an output file which emits assembler code.
class output_file_atmel_generic
The srecord::output_file_ascii_hex class is used to write a file in Atmel Generic format.
class output_file_basic
The srecord::output_file_basic class is used to emit record in BASIc format, using DATA statements.
class output_file_binary
The srecord::output_file_binary class is used to represent an output file in raw binary format.
class output_file_brecord
The srecord::output_file_brecord class is used to represent an output files in Motorola MC68EZ328 bootstrap b-record format.
class output_file_c
The srecord::output_file_c class is used to represent an output file which emits C code.
class output_file_coe
The srecord::output_file_coe class is used to represent the output state of a file in Coefficient File Format (Xilinx).
class output_file_cosmac
The srecord::output_file_cosmac class is used to represent an output which emits RCA Cosmac format.
class output_file_dec_binary
The srecord::output_file_dec_binary class is used to write a DEC Binary (XXDP) formatted file.
class output_file_emon52
The srecord::output_file_emon52 class is used to write an EMON52 formatted file (Elektor Monitor, dunno what the 52 is for).
class output_file_fairchild
The srecord::output_file_fairchild class is used to represent the running state when writing a file in Fairchild Fairbug format.
class output_file_fastload
The srecord::output_file_fastload class is used to write an LSI Logic Fast Load formatted file.
class output_file_formatted_binary
The srecord::output_file_formatted_binary class is used to represent the current state when writing a file in the Formatted Binary format.
class output_file_forth
The srecord::output_file_forth class is used to write a file that can be read by a FORTH system.
class output_file_four_packed_code
The srecord::output_file_four_packed_code class is used to emit files in the Four Packed Code (FPC) format.
class output_file_hexdump
The srecord::output_file_hexdump class is used to represent an output file which emits a hexadecimal dump (including ASCII) of the data.
class output_file_idt
The srecord::output_file_idt class is used to represent an output file which emits Integrated Device Technology (IDT) system integration module (IDT/sim) binary format.
class output_file_intel
The srecord::output_file_intel class is used to write an EPROM load file in Intel Hex format.
class output_file_intel16
The srecord::output_file_intel16 class is used to write an EPROM load file in INHX16 format.
class output_file_logisim
The output_file_logisim class is used to represent the processing neccessry to write a Logisim ROM file.
class output_file_mem
The srecord::output_file_mem class is used to represent the output state of a file in Memory Initialization File Format (.mem Lattice).
class output_file_mif
The srecord::output_file_mif class is used to represent the output state of a file in Memory Initialization File (MIF) format (Altera).
class output_file_mips_flash
The output_file_mips_flash class is used to write a MIPS-Flash formatted file.
class output_file_mos_tech
The srecord::output_file_mos_tech class is used to write a MOS Technology formatted file.
class output_file_motorola
The srecord::output_file_motorola class is used to represent an output file which emits Motorola S-Record format.
class output_file_msbin
The srecord::output_file_msbin class is used to represent an output file in Windows CE Binary Image Data Format.
class output_file_needham
The srecord::output_file_needham class is used to represent.
class output_file_os65v
The srecord::output_file_os65v class is used to represent the file state of an OS65V output file, in OS65V format.
class output_file_ppb
The output_file_ppb class is used to represent the processing required to write a Stag Prom Programmer binary file.
class output_file_ppx
The output_file_ppx class is used to represent the processing required to write a file in PPX or Stag Hex format.
class output_file_signetics
The srecord::output_file_signetics class is used to represent output to a file using the Signetiocs format.
class output_file_spasm
The srecord::output_file_spasm class is used to represent an output files in SPASM format.
class output_file_spectrum
The srecord::output_file_spectrum class is used to represent the running state when writing a file in Spectrum format.
class output_file_stewie
The srecord::output_file_stewie class is used to represent the current state of an output file in an undocumented binary format loosely based on the Motorola format.
class output_file_tektronix
The srecord::output_file_tektronix class is used to represent an output file which is in Tektronix format.
class output_file_tektronix_extended
The srecord::output_file_tektronix_extended class is used to represent an output file which is in Tektronix Extended format.
class output_file_ti_tagged
The srecord::output_file_ti_tagged class is used to represent the output state of a file in Texas Instruments Tagged format.
class output_file_ti_tagged_16
The srecord::output_file_ti_tagged_16 class is used to represent the output state of a file in Texas Instruments SDSMAC (320) format.
class output_file_ti_txt
The srecord::output_file_ti_txt class is used to write a file in ti_txt (MSP430) format.
class output_file_trs80
The srecord::output_file_trs80 class is used to write a TRS-80 binary file.
class output_file_vhdl
The srecord::output_file_vhdl class is used to represent the state out an output file in VHDL format.
class output_file_vmem
The srecord::output_file_vmem class is used to write a file in Verilog VMEM format, to be loaded using the $readmemh() call.
class output_file_wilson
The srecord::output_file_wilson class is used to represent an output file which is in "wilson" format.
class output_filter
The output_filter class is used to represent a generic output manipulation.
class output_filter_reblock
The output_filter_reblock class is used to represent a filter that repacks output records so that they exactly align with the output format's preferred block size.
class quit
The quit class is an abstract class for reporting error messages, both fatal and non-fatal.
class quit_exception
The quit_exception class is use to represent a quit handler which throws an exception, rather than call global exit.
class quit_normal
The quit_normal class is used to represent a quit handler which behaves in the "normal" way: print error message son the standard error, and exit via the gloibal exit function.
class quit_prefix
The quit_prefix class is used to filter the messages issued to include a line prefix.
class record
The srecord::record class is used to represent a data record read from a file.
class stm32
The stm32 class is used to represent the running value of a 32-bit cyclic redundancy check of series of bytes, for the STM32 series of microcontrollers.
Enumerations
enum defcon_t { defcon_ignore , defcon_warning , defcon_fatal_error }
enum endian_t { endian_big , endian_little }
Functions
unsigned char bitrev8 (unsigned char value)
The bitrev8 function is used to reverse the order of the bits in an 8-bit number.
unsigned short bitrev16 (unsigned short value)
The bitrev16 function is used to reverse the order of the bits in an 16-bit number.
unsigned long bitrev24 (unsigned long value)
The bitrev24 function is used to reverse the order of the bits in an 24-bit number.
unsigned long bitrev32 (unsigned long value)
The bitrev32 function is used to reverse the order of the bits in an 32-bit number.
unsigned long long bitrev40 (unsigned long long value)
The bitrev40 function is used to reverse the order of the bits in an 40-bit number.
unsigned long long bitrev48 (unsigned long long value)
The bitrev48 function is used to reverse the order of the bits in an 48-bit number.
unsigned long long bitrev56 (unsigned long long value)
The bitrev56 function is used to reverse the order of the bits in an 56-bit number.
unsigned long long bitrev64 (unsigned long long value)
The bitrev64 function is used to reverse the order of the bits in an 64-bit number.
const char * text_from_defcon (defcon_t x)
int defcon_from_text (const char *text)
const char * endian_to_string (endian_t x)
The endian_to_string function may be used to convert an endian value into its string equivalent.
unsigned short decode_word_be (const unsigned char *data)
The decode_word_be function is used to decode a big-endian 2-byte data buffer into an unsigned short value.
unsigned short decode_word_le (const unsigned char *data)
The decode_word_le function is used to decode a little-endian 2-byte data buffer into an unsigned short value.
unsigned short endian_decode_word (const unsigned char *data, endian_t order)
The decode_word_le function is used to decode a little-endian 2-byte data buffer into an unsigned short value.
interval input_interval (srecord::input::pointer)
The srecord::input_interval function is used to read an input stream and build an interval based on the addresses which contain data within the input.
bool operator== (const interval &lhs, const interval &rhs)
The equality operator is used to determine if two intervals are the same.
bool operator!= (const interval &lhs, const interval &rhs)
The inequality operator is used to determine if two intervals are different.
interval operator* (const interval &lhs, const interval &rhs)
The binary star operator is used to calculate the intersection of two intervals.
interval & operator*= (interval &lhs, const interval &rhs)
The star-and-replace operator is used to calculate the intersection of two intervals, and assign the result to the left-hand-side.
interval operator+ (const interval &lhs, const interval &rhs)
The binary plus operator is used to calculate the union of two intervals.
interval & operator+= (interval &lhs, const interval &rhs)
The plus-and-replace operator is used to calculate the union of two intervals, and assign the result to the left-hand-side.
interval operator- (const interval &lhs, const interval &rhs)
The binary minus operator is used to calculate the difference of two intervals.
interval & operator-= (interval &lhs, const interval &rhs)
The minus-and-replace operator is used to calculate the difference of two intervals, and assign the result to the left-hand-side.
interval operator- (const interval &arg)
The unary minus operator is used to calculate the logical complement (inverse, negative) of an interval.
std::ostream & operator<< (std::ostream &os, const interval &val)
The binary left-shift operator is used to print an interval on an output stream.
bool operator== (const srecord::memory_chunk &, const srecord::memory_chunk &)
bool operator!= (const srecord::memory_chunk &, const srecord::memory_chunk &)
std::string pretty_size (long long x, int width=0)
The pretty_size function is used to convert a number into a smaller number with a multiplying suffix (kMGT...).
void progname_set (char *)
The progname_set function is used by main() to set the name of the currently executing programme.
const char * progname_get ()
The progname_get function is used to retrieve the name of the currently executing programme.
unsigned long r250 (void)
The r250 function is used to produce a 32-bit random number.
std::string string_url_encode (const std::string &text)
The string_url_encode function build a new string by adding url quoting ("$FF")
std::string string_url_decode (const std::string &text)
The string_url_decode function build a new string by removing url quoting ("$FF")
std::string string_quote_c (const std::string &text)
const char * version_stamp (void)
The version_stamp function is used to obtain the version number, as a string.
const char * copyright_years (void)
The copyright_years function is used to obtain the range of copyright years for the copyright notice.
const char * git_sha1 (void)
The git_sha1 function is used to obtain the git hash as a string.
void print_version (void)
The print_version function is used to print the program version, and brief copyright notice, to the standard output.
Variables
quit & quit_default
The quit_default variable is a reference to a quit implementation.
Enumeration Type Documentation
defcon_t
enum srecord::defcon_t
Enumerator
defcon_ignore
defcon_warning
defcon_fatal_error
Definition at line 25 of file defcon.h.
endian_t
enum srecord::endian_t
Enumerator
endian_big
endian_little
Definition at line 26 of file endian.h.
Function Documentation
bitrev8()
unsigned char srecord::bitrev8 (unsigned char value)
The bitrev8 function is used to reverse the order of the bits in an 8-bit number.
This function is its own inverse.
Parameters
value The value to be reversed.
bitrev16()
unsigned short srecord::bitrev16 (unsigned short value)
The bitrev16 function is used to reverse the order of the bits in an 16-bit number.
This function is its own inverse.
Parameters
value The value to be reversed.
bitrev24()
unsigned long srecord::bitrev24 (unsigned long value)
The bitrev24 function is used to reverse the order of the bits in an 24-bit number.
This function is its own inverse.
Parameters
value The value to be reversed.
bitrev32()
unsigned long srecord::bitrev32 (unsigned long value)
The bitrev32 function is used to reverse the order of the bits in an 32-bit number.
This function is its own inverse.
Parameters
value The value to be reversed.
bitrev40()
unsigned long long srecord::bitrev40 (unsigned long long value)
The bitrev40 function is used to reverse the order of the bits in an 40-bit number.
This function is its own inverse.
Parameters
value The value to be reversed.
bitrev48()
unsigned long long srecord::bitrev48 (unsigned long long value)
The bitrev48 function is used to reverse the order of the bits in an 48-bit number.
This function is its own inverse.
Parameters
value The value to be reversed.
bitrev56()
unsigned long long srecord::bitrev56 (unsigned long long value)
The bitrev56 function is used to reverse the order of the bits in an 56-bit number.
This function is its own inverse.
Parameters
value The value to be reversed.
bitrev64()
unsigned long long srecord::bitrev64 (unsigned long long value)
The bitrev64 function is used to reverse the order of the bits in an 64-bit number.
This function is its own inverse.
Parameters
value The value to be reversed.
text_from_defcon()
const char * srecord::text_from_defcon (defcon_t x)
defcon_from_text()
int srecord::defcon_from_text (const char * text)
endian_to_string()
const char * srecord::endian_to_string (endian_t x)
The endian_to_string function may be used to convert an endian value into its string equivalent.
Parameters
x The value to convert
Returns
a C string
decode_word_be()
unsigned short srecord::decode_word_be (const unsigned char * data)
The decode_word_be function is used to decode a big-endian 2-byte data buffer into an unsigned short value.
Parameters
data The data to be decoded
decode_word_le()
unsigned short srecord::decode_word_le (const unsigned char * data)
The decode_word_le function is used to decode a little-endian 2-byte data buffer into an unsigned short value.
Parameters
data The data to be decoded
endian_decode_word()
unsigned short srecord::endian_decode_word (const unsigned char * data, endian_t order)
The decode_word_le function is used to decode a little-endian 2-byte data buffer into an unsigned short value.
Parameters
data The data to be decoded
order The order of the bytes to be decoded.
input_interval()
interval srecord::input_interval (srecord::input::pointer)
The srecord::input_interval function is used to read an input stream and build an interval based on the addresses which contain data within the input.
operator==() [1/2]
bool srecord::operator== (const interval & lhs, const interval & rhs) inline
The equality operator is used to determine if two intervals are the same.
Definition at line 265 of file interval.h.
References srecord::interval::equal().
operator!=() [1/2]
bool srecord::operator!= (const interval & lhs, const interval & rhs) inline
The inequality operator is used to determine if two intervals are different.
Definition at line 275 of file interval.h.
References srecord::interval::equal().
operator*()
interval srecord::operator* (const interval & lhs, const interval & rhs) inline
The binary star operator is used to calculate the intersection of two intervals.
Definition at line 285 of file interval.h.
References srecord::interval::intersection().
operator*=()
interval & srecord::operator*= (interval & lhs, const interval & rhs) inline
The star-and-replace operator is used to calculate the intersection of two intervals, and assign the result to the left-hand-side.
Definition at line 295 of file interval.h.
References srecord::interval::intersection().
operator+()
interval srecord::operator+ (const interval & lhs, const interval & rhs) inline
The binary plus operator is used to calculate the union of two intervals.
Definition at line 306 of file interval.h.
References srecord::interval::union_().
operator+=()
interval & srecord::operator+= (interval & lhs, const interval & rhs) inline
The plus-and-replace operator is used to calculate the union of two intervals, and assign the result to the left-hand-side.
Definition at line 316 of file interval.h.
References srecord::interval::union_().
operator-() [1/2]
interval srecord::operator- (const interval & lhs, const interval & rhs) inline
The binary minus operator is used to calculate the difference of two intervals.
Definition at line 327 of file interval.h.
References srecord::interval::difference().
operator-=()
interval & srecord::operator-= (interval & lhs, const interval & rhs) inline
The minus-and-replace operator is used to calculate the difference of two intervals, and assign the result to the left-hand-side.
Definition at line 337 of file interval.h.
References srecord::interval::difference().
operator-() [2/2]
interval srecord::operator- (const interval & arg) inline
The unary minus operator is used to calculate the logical complement (inverse, negative) of an interval.
Definition at line 348 of file interval.h.
operator<<()
std::ostream & srecord::operator<< (std::ostream & os, const interval & val) inline
The binary left-shift operator is used to print an interval on an output stream.
Definition at line 357 of file interval.h.
References srecord::interval::print().
operator==() [2/2]
bool srecord::operator== (const srecord::memory_chunk & , const srecord::memory_chunk &)
operator!=() [2/2]
bool srecord::operator!= (const srecord::memory_chunk & , const srecord::memory_chunk &)
pretty_size()
std::string srecord::pretty_size (long long x, int width = 0)
The pretty_size function is used to convert a number into a smaller number with a multiplying suffix (kMGT...).
Parameters
x The number to be converted.
width The width of the field you would like to print the number in. More than six is unnecessary.
Returns
a string, including the suffix.
progname_set()
void srecord::progname_set (char *)
The progname_set function is used by main() to set the name of the currently executing programme.
progname_get()
const char * srecord::progname_get ()
The progname_get function is used to retrieve the name of the currently executing programme.
Used by error messages.
r250()
unsigned long srecord::r250 (void)
The r250 function is used to produce a 32-bit random number.
It repeats every 2**256 samples, long enough for most purposes.
string_url_encode()
std::string srecord::string_url_encode (const std::string & text)
The string_url_encode function build a new string by adding url quoting ("$FF")
string_url_decode()
std::string srecord::string_url_decode (const std::string & text)
The string_url_decode function build a new string by removing url quoting ("$FF")
string_quote_c()
std::string srecord::string_quote_c (const std::string & text)
version_stamp()
const char * srecord::version_stamp (void)
The version_stamp function is used to obtain the version number, as a string.
This reflects Aegis' idea of the version, so you can re-create that Aegis version easily.
copyright_years()
const char * srecord::copyright_years (void)
The copyright_years function is used to obtain the range of copyright years for the copyright notice.
This reflects Aegis' tracking of the project, and updated automatically.
git_sha1()
const char * srecord::git_sha1 (void)
The git_sha1 function is used to obtain the git hash as a string.
This reflects git's idea of the version, so you can re-create that git version easily.
print_version()
void srecord::print_version (void)
The print_version function is used to print the program version, and brief copyright notice, to the standard output.
Variable Documentation
quit_default
quit& srecord::quit_default extern
The quit_default variable is a reference to a quit implementation.
It should be used unless there is a good reason not to.